In [30]:
import pandas as pd
Gun = pd.read_csv("GunSeizures.csv") 
Gun.head()
Neighborhoods = {}
for i in Gun['neighborhood']:
    Neighborhoods[i] = 0
for (i, f) in zip(Gun['neighborhood'], Gun['total_count']):
    Neighborhoods[i] += f
data = pd.DataFrame()
neighborhood = list(Neighborhoods.keys())
numguns = list(Neighborhoods.values())
data['neighborhood'] = neighborhood
data['number of confiscated guns'] = numguns
data.head(51
         )

                 neighborhood  number of confiscated guns
0        Mount Oliver Borough                           9
1                    Sheraden                         121
2             Terrace Village                          45
3            Brighton Heights                         149
4                         NaN                        1004
5                    Westwood                          10
6                East Liberty                         148
7         Upper Lawrenceville                          20
8          Marshall-Shadeland                         148
9                   Beechview                         101
10                 East Hills                         137
11                  Arlington                          40
12          Arlington Heights                          10
13           Mount Washington                          90
14           South Side Flats                         208
15                  Hazelwood                         144
16             Homewood South                         345
17                 Greenfield                          25
18                 Bloomfield                          58
19                Beltzhoover                          46
20             Homewood North                         159
21                 Upper Hill                          37
22                Perry South                         136
23   Lincoln-Lemington-Belmar                         136
24          Bedford Dwellings                          83
25              Homewood West                          61
26                    Carrick                         148
27          Central Northside                          83
28                    Chateau                          26
29                   Fineview                          75
30             Chartiers City                           4
31                    Larimer                         126
32                Polish Hill                          10
33                South Shore                          13
34              Highland Park                          42
35                  Knoxville                         119
36        Lower Lawrenceville                          17
37                  Allentown                          91
38      Spring Hill-City View                          77
39                   Garfield                          95
40                      Bluff                          58
41                  Overbrook                          29
42          South Side Slopes                          40
43  Central Business District                         125
44                 Banksville                          10
45                Perry North                          44
46                 Friendship                           5
47           Crawford-Roberts                          57
48                Middle Hill                          96
49                  Brookline                          79
50               Point Breeze                          30